County Priority
Gr770/CK3-Community-Title-Project pull request #95
Opened 2020-10-16 02:09 UTC by Gr770

2020-10-16 06:27 UTC, Charanraja123 requested changes
Overall, I think I have no problems raising the base - which as per you calculations is 19 technically (Since we add one for culture group anyway). 

In Any case, My Main Issue is that, culture and cultural groups have the same priority in your rework. Either we lower cultural group by one or increase cultures by 1. They should not be the same for obvious reason

2020-10-16 06:27 UTC, Charanraja123 commented on common/flavorization/00_CTP.txt
> +	priority = 30
Should be 20

2020-10-16 06:27 UTC, Charanraja123 commented on common/flavorization/00_CTP.txt
> +	priority = 32
what happened here?

2020-10-17 01:23 UTC, Gr770 commented on common/flavorization/00_CTP.txt
> +	priority = 32
should be 21, i had my hand 1 over

2020-10-17 06:10 UTC, Charanraja123 commented
I've made some slight changes, for it to differentiate between culture groups and cultures. also to be in line with the rules we used.

2020-10-18 07:11 UTC, Charanraja123 commented
I've changed stuff, and Fixed until the Brythonic Culture Group.

There are two errors. All Barons got 153 instead of 103 (My fault during find and replace). 
Independent counts got 113 instead of 114. 

Rest of them Seem fine. So priority change is almost done.

2020-10-20 05:23 UTC, Charanraja123 approved these changes

2020-10-20 08:04 UTC, merged